#!/bin/bash -x

# usage: bcheckall [bitsPerWord]

CHECK=Judy1LHCheck

BITS=${1:-64}
for i in `seq 16 3 25` `seq 10 15` `seq 30 -1 28` `seq $BITS -3 31` `seq 17 3 26` `seq 18 3 27`
do
    echo $i
    if ! ( ${CHECK} -B$i && ${CHECK} -B$i -S1 && ${CHECK} -B$i -DS1 )
    then
        exit 1
    fi
done

