#!/bin/bash

# usage: checkall [bitsPerWord]

function report {
    echo
    echo Successes: $SUCCESSES
    echo Failures: $FAILURES
    echo
}

trap "echo; report; exit 2" SIGHUP SIGINT SIGTERM

if [ -x Judy1LHCheck ]
then
    CHECK=Judy1LHCheck
else
    CHECK=check
fi

let SUCCESSES=0
let FAILURES=0

bitsPerWord=${1:-64}
for B in `seq 10 $bitsPerWord`
do
    for S_ARG in '' -S1 -DS1
    do
        CMD="$CHECK -B$B $S_ARG"
        echo $CMD
        if $CMD > /dev/null
        then
            let SUCCESSES=$SUCCESSES+1
        else
            let FAILURES=$FAILURES+1
        fi
    done
done

report

if [ $FAILURES -ne 0 ]
then
    exit 1
fi
