#!/bin/bash

function report {
    echo
    echo Successes: $SUCCESSES
    echo Failures: $FAILURES
    echo
}

trap "echo; report; exit 2" SIGHUP SIGINT SIGTERM

if [ -x Judy1LHCheck ]
then
    CHECK=Judy1LHCheck
else
    CHECK=check
fi

let SUCCESSES=0
let FAILURES=0

let B=10
for d_ARG in '' -d
do
for D_ARG in '' -D
do
for S_ARG in '' -S1
do
while [ $B -le 64 ]
do
    CMD="$CHECK -B$B $S_ARG $D_ARG $d_ARG"
    echo $CMD
    if $CMD > /dev/null
    then
        let SUCCESSES=$SUCCESSES+1
    else
        let FAILURES=$FAILURES+1
    fi
    let B=$B+1
    #let B=$B+3
done
let B=$B-54
done
done
done

report

if [ $FAILURES -ne 0 ]
then
    exit 1
fi
