#!/bin/sh -x

# What is the goal of this regression test script?
# How much memory should it require? Should it test and adapt?

# Use a -DDEBUG build.

TIME=Judy1LHTime
CHECK=Judy1LHCheck

# Basic runs we use for performance testing:
# ${TIME} -1m
# ${TIME} -1m -E
# ${TIME} -1m -DS1
# ${TIME} -Lm
# ${TIME} -Lm -E
# ${TIME} -Lm -DS1

# Both Judy1 and JudyL
: \
&& ${CHECK} -B17 -C -S1  \
&& ${CHECK} -B17 -C -DS1 \
&& ${CHECK} -B17 -C      \
&& ${CHECK} -S1  \
&& ${CHECK} -DS1 \
&& ${CHECK}      \
&& :
if [ $? -ne 0 ]
then
    exit 1
fi

# Judy1
: \
&& ${TIME} -W0 -1 -l -Cvdgi -n1e5 -B17 -S1  \
&& ${TIME} -W0 -1 -l -vdgi  -n1e5 -B17 -DS1 \
&& ${TIME} -W0 -1 -l -vdgi  -n1e5 -B17      \
&& ${TIME} -W0 -1 -l -vdgi  -n1e5 -S1  --splay-key-bits=0xff00ffff \
&& ${TIME} -W0 -1 -l -Cvdgi -n1e5 -DS1 --splay-key-bits=0xff00ffff \
&& ${TIME} -W0 -1 -l -vdgi  -n1e5      --splay-key-bits=0xff00ffff \
&& ${TIME} -W0 -1 -l -vdgi  -n1e5 -S1  \
&& ${TIME} -W0 -1 -l -vdgi  -n1e5 -DS1 \
&& ${TIME} -W0 -1 -l -Cvdgi -n1e5      \
&& :
if [ $? -ne 0 ]
then
    exit 1
fi

# JudyL
: \
&& ${TIME} -W0 -L -l -Cvdgi -n1e5 -B17 -S1  \
&& ${TIME} -W0 -L -l -vdgi  -n1e5 -B17 -DS1 \
&& ${TIME} -W0 -L -l -vdgi  -n1e5 -B17      \
&& ${TIME} -W0 -L -l -vdgi  -n1e5 -S1  --splay-key-bits=0xff00ffff \
&& ${TIME} -W0 -L -l -Cvdgi -n1e5 -DS1 --splay-key-bits=0xff00ffff \
&& ${TIME} -W0 -L -l -vdgi  -n1e5      --splay-key-bits=0xff00ffff \
&& ${TIME} -W0 -L -l -vdgi  -n1e5 -S1  \
&& ${TIME} -W0 -L -l -vdgi  -n1e5 -DS1 \
&& ${TIME} -W0 -L -l -Cvdgi -n1e5      \
&& :
if [ $? -ne 0 ]
then
    exit 1
fi

#&& bcheckall 32 \

#&& ${TIME} -W0 -1lmt \
#&& ${TIME} -W0 -RICvdgi -n1000000 \
#&& ${TIME} -W0 -1Lh -n1000000 -S1 --splay-key-bits=0xff00ffff \

exit 0
