#!/bin/sh -x

# What is the goal of this regression test script?
# How much memory should it require? Should it test and adapt?

# Use a -DDEBUG build.

TIME=Judy1LHTime
CHECK=Judy1LHCheck

# Basic runs we use for performance testing:
# ${TIME} -1m
# ${TIME} -1m -E
# ${TIME} -1m -DS1
# ${TIME} -Lm
# ${TIME} -Lm -E
# ${TIME} -Lm -DS1

: \
&& ${TIME} -W0 -B32 -1Lh -n1000000 -S1 --splay-key-bits=0xff00aa00aa00ffff \
&& ${TIME} -W0 -B33 -RICvdgi -n1000000 \
&& ${CHECK} -B17 \
&& ${CHECK} -B17 -S1 \
&& ${CHECK} -B17 -DS1 \
&& ${TIME} -W0 -B25 -1LICvdgi -n100000 --splay-key-bits=0x0400aa00aa00ffff \
&& ${TIME} -W0 -B25 -1LICvdgi -n100000 -DS1 \
   --splay-key-bits=0x0400aa00aa00ffff \
&& ${CHECK} -B25 \
&& ${CHECK} -B25 -S1 \
&& ${CHECK} -B25 -DS1 \
&& ${TIME} -W0 -B25 -1LICvdgi -n100000 \
&& ${TIME} -W0 -B25 -1LICvdgi -n100000 -S1 \
&& ${CHECK} -B33 \
&& ${CHECK} -B33 -S1 \
&& ${CHECK} -B33 -DS1 \
&& ${TIME} -W0 -B25 -1LICvdgi -n100000 -DS1 \
&& ${TIME} -W0 -B25 -1LICvdgi -n100000 -S1 \
   --splay-key-bits=0x0400aa00aa00ffff \
:

#&& bcheckall 64 \
